sudo: true
language: cpp

compiler:
  - gcc

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

addons:
  apt:
    sources:
    - boost-latest
    - llvm-toolchain-precise
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.7
    - g++-5
    - gcc-5

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script: 
 # There is a difference in versions
 - $CXX --version
 - g++ --version
 - qmake
 - cat Makefile
 - make