language: cpp
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - boost-latest
    packages:
    - libboost1.55-all-dev

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools

script:
 - qmake -project
 - qmake BoostGraphTutorial.pro
 - make


